# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/


class @Game
  constructor: ->
    $(document).keydown (e) =>
      switch e.which
        when 32,40,36
          @dropIt()
        when 37
          @move_token_left()
        when 39
          @move_token_right()
        else
          return
      # exit this handler for other keys
      e.preventDefault()
      # prevent the default action (scroll / move caret)
      return
    # Setup 2D array
    @game = new Array(6)
    for n in [0..5]
      @game[n] = new Array(7)
    @prerender()

  dropIt: ()=>
    col =  $('#drop-token').parent().data('col')
    $.post('/api/v1/games/add_token',  {id:window.current_game_id, column: col}, ->
    ).done( ->
      window.game.prerender()
    ).fail( (data)->
      $('#errors').css('display','block')
      $("#errors").html("Invalid Move")
      setTimeout (->
        $('#errors').fadeOut()
      ), 900
    )
  set_won: (is_won, is_red) ->
    if is_won && is_red
      $('#red-won').css('display','block')
    if is_won && !is_red
      $('#blue-won').css('display','block')



  set_token: (is_red)->
    if is_red
      $('#drop-token').addClass('red-token')
      $('#drop-token').removeClass('blue-token')
    else
      $('#drop-token').addClass('blue-token')
      $('#drop-token').removeClass('red-token')

  prerender: ()=>
    $.getJSON "/games/#{window.current_game_id}.json", (data) ->
      gs = JSON.parse(data['games_state'])
      window.game.set_token(data.red_turn)
      window.game.set_won(data.won, data.red_turn)
      for row, x in gs
        for col,y in row
          window.game.game[y][x] = col
      window.game.render()


  render: ()=>
    for x in [0..5]
      for y in [0..6]
        if @game[x][y] == 'r'
          $("#game-col-#{x}-#{y}").html("<div class='red-token'></div>")
        if @game[x][y] == 'b'
          $("#game-col-#{x}-#{y}").html("<div class='blue-token'></div>")
        #$("#game-col-#{x}-#{y}").html(@game[x][y])


  move_token_right: ()->
    col   = $('#drop-token').parent().data('col')
    token = $('#drop-token').detach()
    new_col = col + 1
    if new_col > 6
      new_col = 0
    token.appendTo($("#entry-col-#{new_col}"))

  move_token_left: ()->
    col   = $('#drop-token').parent().data('col')
    token = $('#drop-token').detach()
    new_col = col - 1
    if new_col < 0
      new_col = 6
    token.appendTo($("#entry-col-#{new_col}"))

$ ->
  window.game = new Game()


# ---
# generated by js2coffee 2.2.0